### ISSUE TITLE
Problem Loading Weights?

### ISSUE THREAD

**Issue by MotorCityCobra** [llSourcell/AI_Artist#3]
Traceback (most recent call last):
  File "/Users/MyName/Desktop/Artist/Network.py", line 292, in <module>
    load_weights(weights_path, model)
  File "/Users/MyName/Desktop/Artist/Network.py", line 85, in load_weights
    model.layers[k].set_weights(weights)
  File "/Users/MyName/anaconda/lib/python3.5/site-packages/keras/engine/topology.py", line 889, in set_weights
    'provided weight shape ' + str(w.shape))
Exception: Layer weight shape (3, 3, 512, 64) not compatible with provided weight shape (64, 3, 3, 3)

**Comment by Naresh1318** [comment]
Even I'm getting the same issue

**Comment by mbaytas** [comment]
Try this: https://github.com/llSourcell/AI_Artist/pull/6/commits/36ca7dfe81e44561552d0820ff71f5eb91fde75d

**Comment by un-knight** [comment]
@MotorCityCobra Have you fix the problem? I have the same issue now.

**Comment by Naresh1318** [comment]
Ok, I found this : 'The code and the provided "vgg16_weights.h5" file follow Theano conventions for dimension ordering. Due to recent updates in the libraries, this won't work. Using a Theano backend in its entirety also won't work without modifying the rest of the code. This is perhaps the quickest way to solve this issue.'

llSourcell/AI_Artist@36ca7df

So adding this line after importing keras backend fixed the error : K.set_image_dim_ordering('th')

**Comment by un-knight** [comment]
@Naresh1318 In fact, I have added the code, but still meet this issue. And my exception is `Layer weight shape (64, 5, 3, 3) not compatible with provided weight shape (64, 3, 3, 3)` . Do you know how to solve this?

**Comment by mbaytas** [comment]
@un-knight Which line in the code is throwing this error?

**Comment by MotorCityCobra** [comment]
I solved the problem by running this, (with all dependancies) in a Conda environment
In my short time using machine learning I'm figuring out they should always be run in a virtual environment with Conda or Virtualenv.
Having Xcode with the corresponding Command Line Tools version (available on the Xcode download page), and an up to date Homebrew installed helps too.

**Comment by un-knight** [comment]
Traceback (most recent call last):
  File "Network.py", line 294, in <module>
    load_weights(weights_path, model)
  File "Network.py", line 85, in load_weights
    model.layers[k].set_weights(weights)
  File "/home/shiyanlou/Code/new_project/venv/local/lib/python2.7/site-packages/keras/engine/topology.py", line 889, in set_weights
    'provided weight shape ' + str(w.shape))
Exception: Layer weight shape (64, 5, 3, 3) not compatible with provided weight shape (64, 3, 3, 3)
@mbaytas This is my error, do you know how to solve it?

**Comment by carlylou** [comment]
@un-knight Hi, I encountered the same error!!! Do you know how to solve it? Thanks in advance.

**Comment by nbomberger** [comment]
Tried everything under the sun - Need to use keras 1.2.2 for 3rd party support, so I can't upgrade to 2.00.

```import os
import pickle
import coremltools
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import h5py as h5py
from skimage import io
from sklearn.model_selection import train_test_split

from keras.models import Sequential, model_from_json
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.optimizers import SGD
from keras.utils import np_utils
from keras import backend as K
K.set_image_dim_ordering('tf')

# set up the shape
PUG_IMG_DIR = "../data/pugs_cropped"
IMG_ROWS, IMG_COLS = 224, 224
IMG_CHANNELS = 3

# load the model
n_pug_images = len(os.listdir(PUG_IMG_DIR))
print(n_pug_images)
pug_images = np.zeros((n_pug_images, IMG_CHANNELS, IMG_ROWS, IMG_COLS), dtype="uint8")

for n, image in enumerate(os.listdir(PUG_IMG_DIR)):
    pug_images[n] = io.imread(PUG_IMG_DIR+"/"+image).transpose()

print(pug_images.shape)
pug_labels = np.ones(n_pug_images)

X = np.concatenate([pug_images])
y = np.concatenate([pug_labels])
# plt.axis('off')
# plt.imshow(pug_images[10].transpose())
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, stratify=y)

with open("../data/pugs_data.pkl.gz", "wb") as pickle_file:
    pickle.dump((X_train, X_test, y_train, y_test), pickle_file)

# we're going to use a pre-trained deep network and chop off the
# last dense layer; we'll freeze the weights in the early layers
# and then train just the final set of dense weights
# see https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3
def VGG_16(weights_path=None):
    model = Sequential()
    print("First layer\n")
    print(IMG_ROWS)
    print(IMG_COLS)
    print(IMG_CHANNELS)
    print(pug_images.shape)
    model.add(ZeroPadding2D((1,1),input_shape=(IMG_ROWS, IMG_COLS, IMG_CHANNELS), dim_ordering='tf', trainable=False))
    model.add(Convolution2D(64, 3, 3, activation='relu', trainable=False, input_shape=(IMG_CHANNELS, IMG_ROWS, IMG_COLS)))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(64, 3, 3, activation='relu', trainable=False))
    model.add(MaxPooling2D((2,2), strides=(2,2), trainable=False))

    print("Second layer\n")
    print(IMG_ROWS)
    print(IMG_COLS)
    print(IMG_CHANNELS)
    print(pug_images.shape)
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu', trainable=False))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(128, 3, 3, activation='relu', trainable=False))
    model.add(MaxPooling2D((2,2), strides=(2,2), trainable=False))

    print("Third layer\n")
    print(IMG_ROWS)
    print(IMG_COLS)
    print(IMG_CHANNELS)
    print(pug_images.shape)
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(256, 3, 3, activation='relu', trainable=False))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(256, 3, 3, activation='relu', trainable=False))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(256, 3, 3, activation='relu', trainable=False))
    model.add(MaxPooling2D((2,2), strides=(2,2), trainable=False))

    print("Fourth layer\n")
    print(IMG_ROWS)
    print(IMG_COLS)
    print(IMG_CHANNELS)
    print(pug_images.shape)
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(512, 3, 3, activation='relu', trainable=False))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(512, 3, 3, activation='relu', trainable=False))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(512, 3, 3, activation='relu', trainable=False))
    model.add(MaxPooling2D((2,2), strides=(2,2), trainable=False))

    print("Fifth layer\n")
    print(IMG_ROWS)
    print(IMG_COLS)
    print(IMG_CHANNELS)
    print(pug_images.shape)
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(512, 3, 3, activation='relu', trainable=False))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(512, 3, 3, activation='relu', trainable=False))
    model.add(ZeroPadding2D((1,1), trainable=False))
    model.add(Convolution2D(512, 3, 3, activation='relu', trainable=False))
    model.add(MaxPooling2D((2,2), strides=(2,2), trainable=False))

    print("Final layer\n")
    print(IMG_ROWS)
    print(IMG_COLS)
    print(IMG_CHANNELS)
    print(pug_images.shape)
    model.add(Flatten())
    model.add(Dense(4096, activation='relu', trainable=False))
    model.add(Dropout(0.5))
    model.add(Dense(4096, activation='relu', trainable=False))
    model.add(Dropout(0.5))
    model.add(Dense(1000, activation='softmax'))

    print(model.summary())
    if weights_path:
        model.load_weights(weights_path)

    return model

batch_size = 32
n_classes = 1 
n_epochs = 10

# load our pre-trained model
model = VGG_16('vgg16_weights.h5')

# chop off the final layer
model.layers = model.layers[:-1]

# and add in a new one appropriate to our task
model.add(Dense(n_classes, activation='softmax'))

# train
Y_train = np_utils.to_categorical(y_train, n_classes)
Y_test = np_utils.to_categorical(y_test, n_classes)

sgd = SGD(lr=0.0001, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=["accuracy"])

model.fit(X_train, Y_train, batch_size=batch_size,
                    nb_epoch=n_epochs,
                    validation_data=(X_test, Y_test), shuffle=True)


json_string = model.to_json()
open('./cnn_pug_model_architecture.json', 'w').write(json_string)
model.save_weights('cnn_pug_model_weights.h5')

coreml_model = coremltools.converters.keras.convert(("cnn_pug_model_architecture.json", "cnn_pug_model_weights.h5"), input_names = 'image', image_input_names = 'image', class_labels = ['pug'])
coreml_model.save('pugs.mlmodel')


#architecture = open('cnn_pug_model_architecture.json', 'r')
#loaded_model_json = architecture.read()
#architecture.close()
#loaded_model = model_from_json(loaded_model_json)
#loaded_model.load_weights("cnn_pug_model_weights.h5")

#coreml_model = coremltools.converters.keras.convert(loaded_model, input_names = 'image', image_input_names = 'image', class_labels = ['pug'])
#coreml_model.save('pugs.mlmodel')```

Anyone get this working?  I would love to know how to fix this - I have flipped everyone, tried everything.  Any options??  

Error:

```raceback (most recent call last):
  File "PugClassifier.py", line 134, in <module>
    model = VGG_16('vgg16_weights.h5')
  File "PugClassifier.py", line 125, in VGG_16
    model.load_weights(weights_path)
  File "/Users/nbomberger/miniconda3/envs/machine/lib/python2.7/site-packages/keras/engine/topology.py", line 2708, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/Users/nbomberger/miniconda3/envs/machine/lib/python2.7/site-packages/keras/engine/topology.py", line 2738, in load_weights_from_hdf5_group
    flattened_layers[k].set_weights(weights)
  File "/Users/nbomberger/miniconda3/envs/machine/lib/python2.7/site-packages/keras/engine/topology.py", line 985, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (3, 3, 3, 64) not compatible with provided weight shape (64, 3, 3, 3)```

**Comment by ahmedshah202** [comment]
Below code is working for me 




f = h5py.File('D:/Kaggle/SFDDD/wts/vgg16_weights.h5')
    for k in range(f.attrs['nb_layers']):
        if k >= len(model.layers):
            # we don't look at the last (fully-connected) layers in the savefile
            break
        g = f['layer_{}'.format(k)]
        weights = [g['param_{}'.format(p)] for p in range(g.attrs['nb_params'])]
        layer = model.layers[k]
        if isinstance(layer, Convolution2D):
            weights[0] = np.transpose(np.array(weights[0])[:, :, ::-1, ::-1], (2, 3, 1, 0))
        layer.set_weights(weights)
    f.close()
    print('Model loaded.')
